### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by Hax0rG1rl** [RandomStormProjects/Bluto#2]
Hi, 

Installed the tool as you have described within README file. Tried to make it run. Got the following error: 

"
An unexpected error has occured. Please report the error and it's context to https://github.com/RandomStorm/Bluto/issues, thank you.
[Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/Bluto/doc/sub_interest.txt': in "get_sub_interest"
"

I'm sure that there is an easy fix for :)

Cheers, 

-J

**Comment by darryllane** [comment]
Hello good Sir :) 
I have updated to 1.1.8, try upgrading and if you still have the problem please let me know the OS you installed it on

**Comment by Hax0rG1rl** [comment]
Hi mate, 

Right. So I got the new build. The same error. Have it tried with a Kali 2 Sana, amd64. 

No point into just copying and paste the same error once again. 

Cheers, 

-J

**Comment by darryllane** [comment]
Seems its its not checking the correct location for the files. If you do a 'pip uninstall bluto' it should list where the files are stored. As a work around you could copy the files to the location your system is looking for them. Also I have fixed some logic issues and pushed version 1.1.9. I doubt it will fix your problem but it will of course fix bugs from 1.1.8. Ill look into a more permanent solution for you.

**Comment by darryllane** [comment]
Can you please run the following command and let me know the output: 

`python -c "import site; print(site.getsitepackages())"`

**Comment by darryllane** [comment]
Ok, I think I have a more permanent fix for this, can you please try install the latest dev version and let me know if it solves the problem.

`sudo pip install git+git://github.com/RandomStorm/Bluto@blutodev --upgrade`

**Comment by darryllane** [comment]
Ive not heard anything further on this and its been a week. So I am going to close this issue down, if you are still having problems please feel free to reopen it or open a new ticket.
