### ISSUE TITLE
erros

### ISSUE THREAD

**Issue by RazorCoding** [RandomStormProjects/Bluto#4]
An unexpected error has occured. Please report the error and it's context to https://github.com/RandomStorm/Bluto/issues, thank you.
[Errno 2] No such file or directory: '/usr/lib/python2.7/site-packages/Bluto/doc/sub_interest.txt': in "get_sub_interest"

**Comment by darryllane** [comment]
Could you please let me know the following:
`operating system`
`python version`
It seems some python deployments aren't looking in the correct location for the relevant files. I am currently looking into how to resolve this. There is a work around for now:

Carry out the following to identify the file locations.
`pip uninstall bluto`

It will ask you to confirm and show you the location of the files. Make a note of the location and then copy the relevant files to that location:

```
dl-mac:darryllane$ pip uninstall bluto
Uninstalling Bluto:
/usr/local/bin/bluto
/usr/local/lib/python2.7/site-packages/Bluto-1.1.9-py2.7.egg-info
/usr/local/lib/python2.7/site-packages/Bluto/__init__.py
/usr/local/lib/python2.7/site-packages/Bluto/__init__.pyc
/usr/local/lib/python2.7/site-packages/Bluto/bluto
/usr/local/lib/python2.7/site-packages/Bluto/doc/countries.txt
/usr/local/lib/python2.7/site-packages/Bluto/doc/sub_interest.txt
/usr/local/lib/python2.7/site-packages/Bluto/doc/subdomains-top1mil-20000.txt
/usr/local/lib/python2.7/site-packages/Bluto/doc/user_agents.txt
Proceed (y/n)? 
```

In this instance its `/usr/local/lib/python2.7/site-packages/Bluto/doc/`

We then make a new directory there ;

`sudo mkdir /usr/lib/python2.7/site-packages/Bluto/doc/`

We then copy the files to that location.

`sudo cp /usr/lib/python2.7/site-packages/Bluto/doc/*.txt /usr/lib/python2.7/site-packages/Bluto/doc/`

You should now be able to use `bluto`. I apologies for the lack of a true fix, but I am working on it. Please let me know how you get on.

**Comment by darryllane** [comment]
Ideally I need to be able to recreate this issue to work out a permanent solution. If you could supply the following info that would be great.
OS version
How many pythons do you have install?
`which python`
What versions are they?
`python -V`
How many pips, and which versions?
`which pip`
`pip -V`

```
dl-mac:darryllane$ which pip
/usr/local/bin/pip
dl-mac:darryllane$ which python
/usr/local/bin/python
dl-mac:darryllane$ python -V 
Python 2.7.9
dl-mac:darryllane$ pip -V
pip 1.5.6 from /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg (python 2.7)
dl-mac:darryllane$ 
```

**Comment by RazorCoding** [comment]
[bushido@Arc ~]$ which pip
/usr/bin/vendor_perl/pip
[bushido@Arc ~]$ which python2
/usr/bin/python2
[bushido@Arc ~]$ python2 -V
Python 2.7.10
[bushido@Arc ~]$ pip -V
bad switch V, expected one of: -i -o -b -I -O at /usr/bin/vendor_perl/pip line 175.
[bushido@Arc ~]$ pip --version
pip 1.2
Written by Ed Avis.

Copyright (C) 2002 Ed Avis.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
[bushido@Arc ~]$

**Comment by darryllane** [comment]
Thanks, can you let me know the OS you are using too please. Can you confirm if you are up and running by following the 'work around'?

**Comment by darryllane** [comment]
Can you please try the dev deployment and let me know if it solves the problem.  If it does ill push it to live.

sudo pip install git+git://github.com/RandomStorm/Bluto@blutodev --upgrade

**Comment by RazorCoding** [comment]
it started working..  i had to install a module lxml ..

**Comment by RazorCoding** [comment]
Wild Cards Are Not In Place

Brute Forcing Sub-Domains

```
While you are waiting we will gather email addresses.
```

Gathering Email Addresses From Google and Bing
Traceback (most recent call last):
  File "/usr/bin/bluto", line 584, in <module>
    userCountry, userServer = get_gserver()
  File "/usr/bin/bluto", line 281, in get_gserver
    r = requests.get(r'http://www.telize.com/geoip/', proxies=proxy)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, *_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, *_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: http://www.telize.com/geoip/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f13659d5510>: Failed to establish a new connection: [Errno 111] Connection refused',)))

**Comment by darryllane** [comment]
doh! I left the proxy (debugging) turned on, sigh .. sorry dude. Ill have to add a exception catch to that I seem to forget to remove that on the dev repo quite a bit. 

Can you show the error you recieved regarding `lxml`? Reason I ask is because I dont actually use that directly, it could be a dependant's dependent in which case it should automatically be installed when bluto installs its dependents. Either way, try running
 `sudo pip install git+git://github.com/RandomStorm/Bluto@blutodev --upgrade` again.

**Comment by darryllane** [comment]
I have moved the dev to live, feel free to run 

`sudo pip install git+git://github.com/RandomStorm/Bluto --upgrade`

**Comment by RazorCoding** [comment]
th

**Comment by RazorCoding** [comment]
the code is working properly now.. thank you

**Comment by darryllane** [comment]
Awesome ;)
