### ISSUE TITLE
GeoIP API permentatly offline

### ISSUE THREAD

**Issue by schniggie** [RandomStormProjects/Bluto#6]
Hey,

the script fails because the GeoIP API is offline since today according to http://www.telize.com/.
Please replace that.

Thanks and BR

**Comment by darryllane** [comment]
Yo, yeah tis done. For the moment it will be using another service, but I think I will roll my own. but for now its back up as should be.

sudo pip install git+git://github.com/RandomStorm/Bluto --upgrade

**Comment by darryllane** [comment]
Thanks for the heads up btw ;)
