### ISSUE TITLE
Unexpected error "Name or service not known: in "action_zone_transfer"

### ISSUE THREAD

**Issue by a9e78rauijasdf** [RandomStormProjects/Bluto#7]
Ran bluto on stock Kubuntu 15.10 on a few test domains via nameservers that allow zone transfers - they all return the following error in the middle of the Raw Zone Dump section:

An unexpected error has occured. Please report the error and it's context to https://github.com/RandomStorm/Bluto/issues, thank you.
[Errno -2] Name or service not known: in "action_zone_transfer"

It still returns (correct) data though.

Running bluto towards a domain which does not utilize "vulnerable" nameservers, does not yield the error.

Running v.1.1.14 btw.

**Comment by darryllane** [comment]
Thanks,  will take a look as soon as im back home and get back to you.

**Comment by a9e78rauijasdf** [comment]
?Alright - let me know if I can help.

BR,

Jesper

**Comment by darryllane** [comment]
No worries, I know what the issue is just need to handle the error so wont take long to fix just need to get 10min to do it. Hopefully this weekend.

**Comment by darryllane** [comment]
Can you please upgrade and try it again.

**Comment by a9e78rauijasdf** [comment]
Thanks - how to upgrade?

sudo pip install --upgrade git+git://github.com/RandomStorm/Bluto  did something - the error still appears though.

btw - CTRL - C  doesnt terminate the application.

/Jesper

**Comment by btv** [comment]
`sudo pip install git+git://github.com/RandomStorm/Bluto --upgrade`

(from the README.MD on the landing page)

**Comment by darryllane** [comment]
Has this been resolved?

**Comment by darryllane** [comment]
Im guessing this is now fix in the latest release as Ive not heard anything back. Will be closing this issue. Thanks for raising it.

**Comment by a9e78rauijasdf** [comment]
Im sorry - work is pretty tough on me right now.

I successfully upgraded - having difficulties with dependencies.. zlib1g-dev and python-dev was missing on my machine.

Still fails (now twice though?)

Raw Zone Dump

An unexpected error has occured. Please report the error and it's context to https://github.com/RandomStorm/Bluto/issues, thank you.
[Errno -2] Name or service not known: in "action_zone_transfer"

(partial dns records here)

An unexpected error has occured. Please report the error and it's context to https://github.com/RandomStorm/Bluto/issues, thank you.
[Errno -2] Name or service not known: in "action_zone_transfer"

**Comment by darryllane** [comment]
Arr you willing to direct message me on twitter or email and let me know the target domain? That way I can recreat the issue your experiencing to fix it. Ive not seen the dependency issues you are having before either.  If you let me know the ditro and version I can try recreate the issue.

**Comment by a9e78rauijasdf** [comment]
?Hi again.

Well, the domain in question isnt really useful for you because it seems that the error only appears when querying nameservers that allow zone transfers, and the NS that I use doesnt allow that for external users as yourself.

Im on Ubuntu 15.10. EMail is no problem :)

/Jesper
