### ISSUE TITLE
?

### ISSUE THREAD

**Issue by 00derp** [RandomStormProjects/Bluto#8]
said to write this to you.

[Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/Bluto/doc/sub_interest.txt': in "get_sub_interest"

**Comment by darryllane** [comment]
Apologies I have only just seen this, can you please upgrade to the dev release and let me know if you are getting the same issue.

If you are please let me know what platform you have it installed on.

sudo pip install git+git://github.com/RandomStorm/Bluto@blutodev --upgrade

**Comment by darryllane** [comment]
Bluto 1.1.19 Released, sudo pip install git+git://github.com/RandomStorm/Bluto --upgrade
