### ISSUE TITLE
v1.1.19 - Error when gathering data from google etc

### ISSUE THREAD

**Issue by erwanlr** [RandomStormProjects/Bluto#9]
```
Gathering Data From Google, Bing And LinkedIn
Traceback (most recent call last):
  File "/usr/local/bin/bluto", line 961, in <module>
    userCountry, userServer = action_country_id()
  File "/usr/local/bin/bluto", line 612, in action_country_id
    r = requests.get(r'http://freegeoip.net/json/')
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='freegeoip.net', port=80): Max retries exceeded with url: /json/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x4338050>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
```

Seems like that freegeoip.net is down, resulting in the exception

**Comment by alani1984** [comment]
Hello my friend. I had the same issue and i found the solution.
The problem is the specific URL "http://freegeoip.net". In order to solve this issue you can make the below changes. 

Changes:

**Current code with issue**
if prox == True:
                proxy = {'http' : 'http://127.0.0.1:8080'}
                r = requests.get(r'http://freegeoip.net/json/', proxies=proxy)
                ip = r.json()['ip']
                originCountry = r.json()['country_name'] 
               else:  
                r = requests.get(r'http://freegeoip.net/json/')
                ip = r.json()['ip']
                originCountry = r.json()['country_name']

**New code that you can change in order to run again the python script without problem.**
            if prox == True:
                proxy = {'http' : 'http://127.0.0.1:8080'}
                r = requests.get(r'http://ip-api.com/json/', proxies=proxy)
                ip = r.json()['query']
                originCountry = r.json()['country'] 
                else:  
                r = requests.get(r'http://ip-api.com/json/')
                ip = r.json()['query']
                originCountry = r.json()['country']

**Comment by erwanlr** [comment]
:+1:

**Comment by ethicalhack3r** [comment]
Yea, http://freegeoip.net/json/ seems to be down

**Comment by darryllane** [comment]
Only just seen this. Will look into it tonight and get back to you.

**Comment by darryllane** [comment]
Have updated and released fixed version

sudo pip install git+git://github.com/RandomStorm/Bluto --upgrade

**Comment by erwanlr** [comment]
:+1:
